//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/JoystickController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @JoystickController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @JoystickController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""JoystickController"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""c222bfe8-21c2-4e7c-989e-f101e61b1b63"",
            ""actions"": [
                {
                    ""name"": ""Rotate PTC"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1b781cbd-a985-4747-a493-bc7ca19941dc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate Hook"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f1446b61-4538-4454-be93-8c18100ec9a2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cable Up and down"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2f0629b9-dc62-4bb1-8efa-bcf5c2cfc276"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Restart "",
                    ""type"": ""Button"",
                    ""id"": ""b3cd1362-5898-442a-8ae3-4408b400f717"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d081a253-ee7e-4ef0-8c21-bd923e22755d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate Hook"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f6893f6f-c14e-4582-bed8-ed4c01142d1d"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""59f04b57-4495-4e13-9ea6-58bec28f28ad"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate Hook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1ca4016f-2be8-4f6f-b49f-b6ef0170c74c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cable Up and down"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fcbc3963-38c4-468f-895d-bc4a59945627"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cable Up and down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fd823a02-4bd7-4542-86ac-2182535f981f"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cable Up and down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9e54433b-6439-42b3-91fe-154577724bd4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate PTC"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c884dc70-f6cf-47a7-8e3a-a761291ccf7c"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate PTC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e77dda47-85cc-4e9f-9688-f1ef8e3f8cf3"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate PTC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c5123ef5-506f-409b-be44-a7df1c555b3f"",
                    ""path"": ""<HID::MY-POWER CO.,LTD. SPEEDLINK COMPETITION PRO>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Restart "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_RotatePTC = m_Gameplay.FindAction("Rotate PTC", throwIfNotFound: true);
        m_Gameplay_RotateHook = m_Gameplay.FindAction("Rotate Hook", throwIfNotFound: true);
        m_Gameplay_CableUpanddown = m_Gameplay.FindAction("Cable Up and down", throwIfNotFound: true);
        m_Gameplay_Restart = m_Gameplay.FindAction("Restart ", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_RotatePTC;
    private readonly InputAction m_Gameplay_RotateHook;
    private readonly InputAction m_Gameplay_CableUpanddown;
    private readonly InputAction m_Gameplay_Restart;
    public struct GameplayActions
    {
        private @JoystickController m_Wrapper;
        public GameplayActions(@JoystickController wrapper) { m_Wrapper = wrapper; }
        public InputAction @RotatePTC => m_Wrapper.m_Gameplay_RotatePTC;
        public InputAction @RotateHook => m_Wrapper.m_Gameplay_RotateHook;
        public InputAction @CableUpanddown => m_Wrapper.m_Gameplay_CableUpanddown;
        public InputAction @Restart => m_Wrapper.m_Gameplay_Restart;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @RotatePTC.started += instance.OnRotatePTC;
            @RotatePTC.performed += instance.OnRotatePTC;
            @RotatePTC.canceled += instance.OnRotatePTC;
            @RotateHook.started += instance.OnRotateHook;
            @RotateHook.performed += instance.OnRotateHook;
            @RotateHook.canceled += instance.OnRotateHook;
            @CableUpanddown.started += instance.OnCableUpanddown;
            @CableUpanddown.performed += instance.OnCableUpanddown;
            @CableUpanddown.canceled += instance.OnCableUpanddown;
            @Restart.started += instance.OnRestart;
            @Restart.performed += instance.OnRestart;
            @Restart.canceled += instance.OnRestart;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @RotatePTC.started -= instance.OnRotatePTC;
            @RotatePTC.performed -= instance.OnRotatePTC;
            @RotatePTC.canceled -= instance.OnRotatePTC;
            @RotateHook.started -= instance.OnRotateHook;
            @RotateHook.performed -= instance.OnRotateHook;
            @RotateHook.canceled -= instance.OnRotateHook;
            @CableUpanddown.started -= instance.OnCableUpanddown;
            @CableUpanddown.performed -= instance.OnCableUpanddown;
            @CableUpanddown.canceled -= instance.OnCableUpanddown;
            @Restart.started -= instance.OnRestart;
            @Restart.performed -= instance.OnRestart;
            @Restart.canceled -= instance.OnRestart;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnRotatePTC(InputAction.CallbackContext context);
        void OnRotateHook(InputAction.CallbackContext context);
        void OnCableUpanddown(InputAction.CallbackContext context);
        void OnRestart(InputAction.CallbackContext context);
    }
}
